Sрrint 1
KonstantinLanin/middle.messenger.praktikum.yandex pull request #3
Opened 2023-02-03 12:58 UTC by KonstantinLanin

Есть проблема со стилями, не получилось её решить. К сожалению, команда группы не смогла помочь.

2023-02-03 18:40 UTC, podlovchenko requested changes
Привет, стили не подключаются потому что страницы не собираются вместе с layout, пока не могу принять работу

2023-02-03 18:40 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2023-02-03 18:40 UTC, podlovchenko commented on server.js
> +const port = 3001;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2023-02-03 18:40 UTC, podlovchenko commented on server.js
> +const port = 3001;
Проект должен запускаться на 3000 порту

2023-02-05 04:36 UTC, KonstantinLanin commented
> Привет, стили не подключаются потому что страницы не собираются вместе с layout, пока не могу принять работу

Привет! Да, но мне не понятно почему так происходит и что нужно изменить. Можешь подтолкнуть к идее куда смотреть / что изменить?

2023-02-05 08:57 UTC, podlovchenko requested changes
Еще есть ошибки в импортах в styles.css

2023-02-05 08:57 UTC, podlovchenko commented on handlebars.config.js
> +  layout: "./src/layout",
Здесь необходимо указать
```suggestion
  layouts: "./src/layout",
```

2023-02-05 08:57 UTC, podlovchenko commented on .postcssrc
> +  "modules": true,
```suggestion
  "module": true,
```

2023-02-06 09:21 UTC, podlovchenko approved these changes
Привет, спасибо за проделанную работу, принимаю 👍

2023-02-27 07:38 UTC, closed without merging